#!/usr/bin/env python

import sys
import shutil
from os import makedirs
from os.path import join, expanduser

usage = """
- Symlink 1-0-0 into the top directory of the Escher repository
- Run python setup.py build_gh in the Escher repository

./get_site /path/to/escher-repo

"""

if len(sys.argv) < 2:
    print(usage)
src_dir = expanduser(sys.argv[1])

# copy index
shutil.copy(join(src_dir, 'index.html'), '.')

# copy static
try:
    shutil.rmtree('py')
except OSError:
    pass
makedirs(join('py', 'escher'))
shutil.copytree(join(src_dir, 'py', 'escher', 'static'), join('py', 'escher', 'static'))

# copy builder
try:
    shutil.rmtree('builder')
except OSError:
    pass
builder = 'builder'
shutil.copytree(join(src_dir, builder), join('.', builder))

# Add google analytics
with open('index.html', 'r') as f:
    lines = f.readlines()

index = None
for i, line in enumerate(lines):
    if '</head>' in line:
        index = i
lines.insert(i, "<script>(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)})(window,document,'script','//www.google-analytics.com/analytics.js','ga');ga('create', 'UA-37860890-3', 'auto');ga('send', 'pageview');</script>\n")

with open('index.html', 'w') as f:
    f.write(''.join(lines))
